apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "openad-model.fullname" . }}
  labels:
    {{- include "openad-model.labels" . | nindent 4 }}
  annotations:
    haproxy.router.openshift.io/timeout: 1h
spec:
  to:
    kind: Service
    name: {{ include "openad-model.fullname" . }}
    weight: 100
  port:
    targetPort: http # target port service name default
  wildcardPolicy: None
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
